name: 'Check security by Nudgeer'

on:
  pull_request:
    types:
      - opened

jobs:
  build:
      name: check
      runs-on: ubuntu-latest
      steps:
      - name: Check website
        uses: onboardbase/nudgeer-action@v1
        with:
          domain: "https://kroking.dev"
          wait: '10'